### Pytorch

In [ ]:
import torch, numpy as np

In [39]:
print(torch.__version__) 
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.device)
# print(torch.cuda.get_device_name(0))

2.13.0+cpu
False
0
<class 'torch.cuda.device'>


In [9]:
np_arr = np.array([
    ["Love", "Me"],
    ["I", "Do",]
])

np_arr

array([['Love', 'Me'],
       ['I', 'Do']], dtype='<U4')

In [45]:
# Tensor are for numbers not texts - So the below code will fail
ts_array = torch.tensor(
    [
       ["Love", "Me"],
       ["I", "Do",] 
    ]
)

ValueError: too many dimensions 'str'

In [46]:
# If you actually want to represent "Love", "Me", "I", "Do" as tensor data, you need a step in between:
    
vocab = {"Love": 0, "Me": 1, "I": 2, "Do": 3}

ts_array_vocab = torch.tensor(
    [
        [vocab["Love"], vocab["Me"]],
        [vocab["I"], vocab["Do"]]
    ]
)
ts_array_vocab

tensor([[0, 1],
        [2, 3]])

In [47]:

ts_array = torch.tensor(
    [
        [1, 2],
        [3, 4]
    ]
)
ts_array

tensor([[1, 2],
        [3, 4]])

In [54]:
print(ts_array.shape, ts_array.dtype)

torch.Size([2, 2]) torch.int64


In [56]:
rand = torch.rand(2, 4)
zeros = torch.zeros(3,2)

print("Rand: ", rand)
print("Zeros: ", zeros)

Rand:  tensor([[0.9118, 0.3694, 0.9770, 0.1303],
        [0.0273, 0.9319, 0.1632, 0.7051]])
Zeros:  tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [59]:
a = torch.tensor(
    [2, 3]
)
b = torch.tensor(
    [6, 4]
)

f = 3a^3 - b^2

df/da = 9a^2

df/db = -2b

In [ ]:
f = 3 * a**3 - b**2

print(f"f: {f}")
print(f"df/da: {f}")
print(f"df/db: {f}")

f: tensor([-12,  65])


### Tensor operations

In [61]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)          # element-wise add
print(a * b)          # element-wise multiply
print(a @ b)          # dot product (matrix mult for 1D)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(32)


In [62]:
x = torch.rand(2, 3)
print(x.sum())        # sum all elements
print(x.mean())       # mean
print(x.view(3, 2))   # reshape (like numpy's reshape)
print(x.T)            # transpose

tensor(3.1400)
tensor(0.5233)
tensor([[0.7694, 0.9426],
        [0.2053, 0.2934],
        [0.7977, 0.1316]])
tensor([[0.7694, 0.2934],
        [0.9426, 0.7977],
        [0.2053, 0.1316]])
