### One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [62]:
# Sample Sentences
sentences = [
    "The food is good",
    "The food is bad",
    "Pizza is amazing"
]

print("""
Vocabulary: ['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

the food is good: [
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
]

the food is bad: [
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 0, 0],
]

pizza is amazing: [
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
]

""")


Vocabulary: ['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

the food is good: [
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
]

the food is bad: [
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 0, 0],
]

pizza is amazing: [
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
]




### Code Implementation

In [37]:
# Step 1: Tokenize each sentence into lowercase words

tokenized_sentences = [sentence.lower().split() for sentence in sentences]
print(tokenized_sentences)

[['the', 'food', 'is', 'good'], ['the', 'food', 'is', 'bad'], ['pizza', 'is', 'amazing']]


In [53]:
# Step 2: Build the vocabulary (all unique words across all sentences)

all_words = [words for sentences in tokenized_sentences for words in sentences]
vocabulary = sorted(set(all_words))
vocabulary

['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

In [66]:
# Step 3: Fit OneHotEncoder on the vocabulary
# reshape into a column since OneHotEncoder expects 2D input

import numpy as np
vocab_array = np.array(vocabulary).reshape(-1, 1)
print(vocab_array)

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(vocab_array)


[['amazing']
 ['bad']
 ['food']
 ['good']
 ['is']
 ['pizza']
 ['the']]


,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a SciPy sparse matrix/arrayin ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide <encoder_infrequent_categories>`.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide <encoder_infrequen

In [ ]:
# Step 4: Encode each sentence word-by-word

def encode_sentence(tokens, encoder):
    tokens_array = np.array(tokens).reshape(-1, 1)
    return encoder.transform(tokens_array)

encode_sentence(tokenized_sentences[0], encoder)

array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [ ]:
for sentence, tokens in zip(sentences, tokenized_sentences):
    encoded = encode_sentence(tokens, encoder)
    print(f"\n{sentence}:")
    print(encoded)


The food is good:
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]

The food is bad:
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]

Pizza is amazing:
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


### Using pd.get_dummies

In [74]:
tokenized_sentences = [ sent.lower().split() for sent in sentences ]
tokenized_sentences

[['the', 'food', 'is', 'good'],
 ['the', 'food', 'is', 'bad'],
 ['pizza', 'is', 'amazing']]

In [77]:
all_words = [ w for words in tokenized_sentences for w in words ]
words_series = pd.Series(all_words)
words_series

0         the
1        food
2          is
3        good
4         the
5        food
6          is
7         bad
8       pizza
9          is
10    amazing
dtype: str

In [78]:
dummies = pd.get_dummies(words_series)
dummies

,amazing,bad,food,good,is,pizza,the
0,False,False,False,False,False,False,True
1,False,False,True,False,False,False,False
2,False,False,False,False,True,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,False,True
5,False,False,True,False,False,False,False
6,False,False,False,False,True,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,True,False
9,False,False,False,False,True,False,False


In [79]:
encoded_sentences = []
idx = 0
for tokens in tokenized_sentences:
    n = len(tokens)
    encoded_sentences.append(dummies.iloc[idx:idx+n].values)
    idx += n

for sentence, encoded in zip(sentences, encoded_sentences):
    print(f"\n{sentence}:")
    print(encoded)


The food is good:
[[False False False False False False  True]
 [False False  True False False False False]
 [False False False False  True False False]
 [False False False  True False False False]]

The food is bad:
[[False False False False False False  True]
 [False False  True False False False False]
 [False False False False  True False False]
 [False  True False False False False False]]

Pizza is amazing:
[[False False False False False  True False]
 [False False False False  True False False]
 [ True False False False False False False]]


In [81]:
dummies_new = pd.get_dummies(["love", "good", "food"]).reindex(columns=dummies.columns, fill_value=0)
dummies_new

,amazing,bad,food,good,is,pizza,the
0,0,0,False,False,0,0,0
1,0,0,False,True,0,0,0
2,0,0,True,False,0,0,0


### Using one_hot from tensorflow

In [82]:
from tensorflow.keras.preprocessing.text import one_hot

In [83]:
sentences

['The food is good', 'The food is bad', 'Pizza is amazing']

In [99]:
vocab_size = len(vocabulary) + 1
one_hot_encoder = [ one_hot(sentence.lower(), vocab_size) for sentence in sentences ]
one_hot_encoder

[[7, 2, 2, 7], [7, 2, 2, 1], [5, 2, 3]]

Looking at your output for "the food is bad" -> [7, 2, 2, 1]:

the  -> 7

food -> 2

is   -> 2      <- collision! same index as "food"

bad  -> 1

**Why this makes one_hot risky to use**

This is exactly why most people avoid keras.preprocessing.text.one_hot in real projects. It gives the illusion of one-hot/integer encoding, but:

1. There's no word_index dictionary you can inspect or reverse
2. You cannot guarantee uniqueness, only reduce collision probability by inflating vocab_size well beyond what you actually need
3. Even a generous vocab_size like 50 for a 7-word vocabulary can still produce collisions, since it's random hashing, not smart allocation

In [100]:
vocab_size = 2
one_hot_encoder = [ one_hot(sentence.lower(), vocab_size) for sentence in sentences ]
one_hot_encoder

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1]]

### The fix: use Tokenizer instead

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

# num_words is optional, and you only add it when you actually want to truncate a large vocabulary. 
# For small datasets, skip it entirely.
# tokenizer = Tokenizer(num_words=voc_size)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

print(f"Word Index: {tokenizer.word_index}")
# {'is': 1, 'the': 2, 'food': 3, 'good': 4, 'bad': 5, 'pizza': 6, 'amazing': 7}

sequences = tokenizer.texts_to_sequences(sentences)
print(f"Sequences: {sequences}")
# [[2, 3, 1, 4], [2, 3, 1, 5], [6, 1, 7]]

Word Index: {'is': 1, 'the': 2, 'food': 3, 'good': 4, 'bad': 5, 'pizza': 6, 'amazing': 7}
Sequences: [[2, 3, 1, 4], [2, 3, 1, 5], [6, 1, 7]]


In [130]:
hash("love") % 30

5

In [131]:
# ["the", "food", "is", "good"]
[hash("the") % 30, hash("food") % 30, hash("is") % 30, hash("good") % 30]

[8, 16, 9, 26]

### Word Embeddings using Tokenizer (Fixing the Collision Problem)

*Using `Tokenizer` instead of `one_hot()` to avoid hash collisions, then feeding the sequences into a Keras `Embedding` layer.*

In [119]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np

sentences = [
    "The food is good",
    "The food is bad",
    "Pizza is amazing"
]

In [120]:
# Step 1: Fit the tokenizer on our sentences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'is': 1, 'the': 2, 'food': 3, 'good': 4, 'bad': 5, 'pizza': 6, 'amazing': 7}


In [121]:
# Step 2: Convert sentences into integer sequences
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)

[[2, 3, 1, 4], [2, 3, 1, 5], [6, 1, 7]]


In [122]:
# Step 3: Define vocab size (+1 for reserved padding index 0)
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

8


In [123]:
# Step 4: Pad sequences so they're all the same length
sent_length = max(len(seq) for seq in sequences)  # longest sentence = 4
padded_docs = pad_sequences(sequences, padding='pre', maxlen=sent_length)
print(padded_docs)

[[2 3 1 4]
 [2 3 1 5]
 [0 6 1 7]]


In [124]:
# Step 5: Build the Embedding model
dim = 10  # size of each word's embedding vector

model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

model.summary()

c:\Users\khem6\miniconda3\envs\gen-ai\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [125]:
# Step 6: Generate embeddings for all sentences
embedded_docs = model.predict(padded_docs)
embedded_docs

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 550ms/step


array([[[ 0.00262872,  0.03076719, -0.01157931,  0.01556515,
         -0.02421829, -0.04438434, -0.04509257,  0.03640005,
         -0.03214002,  0.00351896],
        [ 0.04566736,  0.04182359, -0.02339085,  0.04453571,
          0.000832  ,  0.00733738, -0.01949877, -0.01316203,
         -0.03133078, -0.03703787],
        [-0.01967117,  0.02720772, -0.03591348,  0.04561311,
          0.0471087 ,  0.01819466, -0.01665945, -0.03410532,
          0.01961669, -0.04879247],
        [-0.0393819 ,  0.00374009,  0.03450255,  0.02054631,
         -0.01658466, -0.04926829,  0.0487478 ,  0.02078117,
          0.00631357, -0.01516   ]],

       [[ 0.00262872,  0.03076719, -0.01157931,  0.01556515,
         -0.02421829, -0.04438434, -0.04509257,  0.03640005,
         -0.03214002,  0.00351896],
        [ 0.04566736,  0.04182359, -0.02339085,  0.04453571,
          0.000832  ,  0.00733738, -0.01949877, -0.01316203,
         -0.03133078, -0.03703787],
        [-0.01967117,  0.02720772, -0.03591348,  0

In [126]:
# Step 7: Inspect a single sentence's embedding
print(padded_docs[0])
print(embedded_docs[0])

[2 3 1 4]
[[ 0.00262872  0.03076719 -0.01157931  0.01556515 -0.02421829 -0.04438434
  -0.04509257  0.03640005 -0.03214002  0.00351896]
 [ 0.04566736  0.04182359 -0.02339085  0.04453571  0.000832    0.00733738
  -0.01949877 -0.01316203 -0.03133078 -0.03703787]
 [-0.01967117  0.02720772 -0.03591348  0.04561311  0.0471087   0.01819466
  -0.01665945 -0.03410532  0.01961669 -0.04879247]
 [-0.0393819   0.00374009  0.03450255  0.02054631 -0.01658466 -0.04926829
   0.0487478   0.02078117  0.00631357 -0.01516   ]]


5